import { Routes } from '@angular/router';

import { authGuard } from './core/guards/auth.guard';
import { roleGuard } from './core/guards/role.guard';

const admin = ['Admin'];
const operational = ['Admin', 'Manager'];
const authenticated = ['Admin', 'Manager', 'Cashier'];

export const routes: Routes = [
  {
    path: '',
    canActivate: [authGuard],
    loadComponent: () => import('./layout/main-layout/main-layout.component').then(m => m.MainLayoutComponent),
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'account-pending', loadComponent: () => import('./features/auth/account-pending/account-pending.component').then(m => m.AccountPendingComponent) },
      { path: 'change-password', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/auth/change-password/change-password.component').then(m => m.ChangePasswordComponent) },
      { path: 'dashboard', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/dashboard/dashboard.component').then(m => m.DashboardComponent) },
      { path: 'admin/dashboard', canActivate: [roleGuard], data: { roles: admin }, loadComponent: () => import('./features/dashboard/dashboard.component').then(m => m.DashboardComponent) },
      { path: 'manager/dashboard', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/dashboard/dashboard.component').then(m => m.DashboardComponent) },
      { path: 'user/dashboard', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/dashboard/dashboard.component').then(m => m.DashboardComponent) },

      { path: 'products', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/products/product-list/product-list.component').then(m => m.ProductListComponent) },
      { path: 'products/new', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/products/product-form/product-form.component').then(m => m.ProductFormComponent) },
      { path: 'products/:id/edit', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/products/product-form/product-form.component').then(m => m.ProductFormComponent) },
      { path: 'products/:id', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/brands/brand-detail/brand-detail.component').then(m => m.BrandDetailComponent) },
      { path: 'products/:id/prices', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/prices/price-list/price-list.component').then(m => m.PriceListComponent) },
      { path: 'products/:id/price-history', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/products/product-price-history.component').then(m => m.ProductPriceHistoryComponent) },
      { path: 'product-groups', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/product-groups/product-group-list.component').then(m => m.ProductGroupListComponent) },
      { path: 'product-groups/:id', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/product-groups/product-group-detail.component').then(m => m.ProductGroupDetailComponent) },
      { path: 'brands', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/brands/brand-list/brand-list.component').then(m => m.BrandListComponent) },
      { path: 'brands/search', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/brands/brand-search/brand-search.component').then(m => m.BrandSearchComponent) },
      { path: 'brands/:id', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/brands/brand-detail/brand-detail.component').then(m => m.BrandDetailComponent) },
      { path: 'generics', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/generics/generic-list.component').then(m => m.GenericListComponent) },
      { path: 'companies', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/companies/company-list.component').then(m => m.CompanyListComponent) },
      { path: 'companies/:id/products', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/companies/company-products/company-products.component').then(m => m.CompanyProductsComponent) },
      { path: 'units', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/units/unit-list.component').then(m => m.UnitListComponent) },
      { path: 'dosage-forms', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/dosage-forms/dosage-form-list.component').then(m => m.DosageFormListComponent) },

      { path: 'sales', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/sales/sale-list/sale-list.component').then(m => m.SaleListComponent) },
      { path: 'sales/new', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/sales/sale-form/sale-form.component').then(m => m.SaleFormComponent) },
      { path: 'sales/:id', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/sales/sale-view/sale-view.component').then(m => m.SaleViewComponent) },
      { path: 'purchases', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/purchases/purchase-list/purchase-list.component').then(m => m.PurchaseListComponent) },
      { path: 'purchases/new', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/purchases/purchase-form/purchase-form.component').then(m => m.PurchaseFormComponent) },
      { path: 'purchases/:id', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/purchases/purchase-view/purchase-view.component').then(m => m.PurchaseViewComponent) },
      { path: 'purchases/:id/payment', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/purchases/purchase-payment/purchase-payment.component').then(m => m.PurchasePaymentComponent) },
      { path: 'purchases/:id/edit', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/purchases/purchase-form/purchase-form.component').then(m => m.PurchaseFormComponent) },
      { path: 'purchase-orders', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/purchases/purchase-orders/purchase-order-list/purchase-order-list.component').then(m => m.PurchaseOrderListComponent) },
      { path: 'purchase-orders/new', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/purchases/purchase-orders/purchase-order-form/purchase-order-form.component').then(m => m.PurchaseOrderFormComponent) },
      { path: 'purchase-orders/:id', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/purchases/purchase-orders/purchase-order-view/purchase-order-view.component').then(m => m.PurchaseOrderViewComponent) },
      // { path: 'purchase-orders/:id/edit', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/purchases/purchase-orders/purchase-order-form/purchase-order-form.component').then(m => m.PurchaseOrderFormComponent) },
      { path: 'purchase-requirements', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/purchases/purchase-requirements/purchase-requirements.component').then(m => m.PurchaseRequirementsComponent) },

      { path: 'returns/sale', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/returns/sale-return-list/sale-return-list.component').then(m => m.SaleReturnListComponent) },
      { path: 'returns/sale/new', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/returns/sale-return-form/sale-return-form.component').then(m => m.SaleReturnFormComponent) },
      { path: 'returns/sale/:id', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/returns/sale-return-detail/sale-return-detail.component').then(m => m.SaleReturnDetailComponent) },
      { path: 'returns/purchase', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/returns/purchase-return-list/purchase-return-list.component').then(m => m.PurchaseReturnListComponent) },
      { path: 'returns/purchase/new', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/returns/purchase-return-form/purchase-return-form.component').then(m => m.PurchaseReturnFormComponent) },
      { path: 'returns/purchase/:id', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/returns/purchase-return-detail/purchase-return-detail.component').then(m => m.PurchaseReturnDetailComponent) },

      { path: 'suppliers', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/suppliers/supplier-list/supplier-list.component').then(m => m.SupplierListComponent) },
      { path: 'suppliers/new', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/suppliers/supplier-form/supplier-form.component').then(m => m.SupplierFormComponent) },
      // { path: 'suppliers/:id/edit', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/suppliers/supplier-form/supplier-form.component').then(m => m.SupplierFormComponent) },
      { path: 'suppliers/:id/products', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/suppliers/supplier-products/supplier-products.component').then(m => m.SupplierProductsComponent) },
      { path: 'suppliers/:id/purchases', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/suppliers/supplier-purchase-history/supplier-purchase-history.component').then(m => m.SupplierPurchaseHistoryComponent) },
      { path: 'suppliers/:id/payments', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/suppliers/supplier-payment-list/supplier-payment-list.component').then(m => m.SupplierPaymentListComponent) },

      { path: 'inventory', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/inventory/inventory.component').then(m => m.InventoryComponent) },
      { path: 'warehouses', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/warehouses/warehouse-list/warehouse-list.component').then(m => m.WarehouseListComponent) },
      { path: 'warehouses/new', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/warehouses/warehouse-form/warehouse-form.component').then(m => m.WarehouseFormComponent) },
      { path: 'warehouses/:id', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/warehouses/warehouse-detail/warehouse-detail.component').then(m => m.WarehouseDetailComponent) },
      // { path: 'warehouses/:id/edit', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/warehouses/warehouse-form/warehouse-form.component').then(m => m.WarehouseFormComponent) },
      { path: 'stock-transfers', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/stock-transfers/stock-transfers.component').then(m => m.StockTransfersComponent) },
      { path: 'expired', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/expired-products/expired-product-list/expired-product-list.component').then(m => m.ExpiredProductListComponent) },
      { path: 'expired/near-expiry', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/expired-products/near-expiry-list/near-expiry-list.component').then(m => m.NearExpiryListComponent) },
      { path: 'expired/history', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/expired-products/expired-history/expired-history.component').then(m => m.ExpiredHistoryComponent) },
      { path: 'expired/pending-approvals', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/expired-products/pending-approvals/pending-approvals.component').then(m => m.PendingApprovalsComponent) },
      { path: 'damage', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/damage/damage-list.component').then(m => m.DamageListComponent) },
      { path: 'damage/new', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/damage/damage-form.component').then(m => m.DamageFormComponent) },
      { path: 'damage/view/:id', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/damage/damage-detail.component').then(m => m.DamageDetailComponent) },
      { path: 'damage/edit/:id', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/damage/damage-form.component').then(m => m.DamageFormComponent) },
      { path: 'damage/pending-approvals', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/damage/damage-pending-approvals.component').then(m => m.DamagePendingApprovalsComponent) },

      { path: 'doctors', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/doctors/doctor-list.component').then(m => m.DoctorListComponent) },
      { path: 'prescriptions', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/prescriptions/prescription-list/prescription-list.component').then(m => m.PrescriptionListComponent) },
      { path: 'prescriptions/new', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/prescriptions/prescription-form/prescription-form.component').then(m => m.PrescriptionFormComponent) },
      // { path: 'prescriptions/:id/edit', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/prescriptions/prescription-form/prescription-form.component').then(m => m.PrescriptionFormComponent) },
      { path: 'customers', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/customers/customer-list/customer-list.component').then(m => m.CustomerListComponent) },
      { path: 'customers/new', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/customers/customer-form/customer-form.component').then(m => m.CustomerFormComponent) },
      { path: 'customers/edit/:id', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/customers/customer-form/customer-form.component').then(m => m.CustomerFormComponent) },
      { path: 'customers/:id/orders', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/customers/customer-order-history/customer-order-history.component').then(m => m.CustomerOrderHistoryComponent) },
      { path: 'employees', canActivate: [roleGuard], data: { roles: admin }, loadComponent: () => import('./features/hr/employee-list/employee-list.component').then(m => m.EmployeeListComponent) },
      { path: 'employees/new', canActivate: [roleGuard], data: { roles: admin }, loadComponent: () => import('./features/hr/employee-form/employee-form.component').then(m => m.EmployeeFormComponent) },
      { path: 'employees/:id', canActivate: [roleGuard], data: { roles: admin }, loadComponent: () => import('./features/hr/employee-details/employee-details.component').then(m => m.EmployeeDetailsComponent) },
      // { path: 'employees/:id/edit', canActivate: [roleGuard], data: { roles: admin }, loadComponent: () => import('./features/hr/employee-form/employee-form.component').then(m => m.EmployeeFormComponent) },

      { path: 'reports', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/reports/reports.component').then(m => m.ReportsComponent) },
      { path: 'ledger', canActivate: [roleGuard], data: { roles: admin }, loadComponent: () => import('./features/accounting/ledger/ledger.component').then(m => m.LedgerComponent) },
      { path: 'payment-methods', canActivate: [roleGuard], data: { roles: admin }, loadComponent: () => import('./features/payment-methods/payment-methods.component').then(m => m.PaymentMethodsComponent) },
      { path: 'sms-logs', canActivate: [roleGuard], data: { roles: admin }, loadComponent: () => import('./features/sms-logs/sms-log-list.component').then(m => m.SmsLogListComponent) },
      { path: 'activity-log', canActivate: [roleGuard], data: { roles: admin }, loadComponent: () => import('./features/admin/activity-log/activity-log.component').then(m => m.ActivityLogComponent) },
      { path: 'users-roles', canActivate: [roleGuard], data: { roles: admin }, loadComponent: () => import('./features/admin/users-roles/users-roles.component').then(m => m.UsersRolesComponent) },

      { path: 'suppliers/edit/:id', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/suppliers/supplier-form/supplier-form.component').then(m => m.SupplierFormComponent) },
      { path: 'warehouses/edit/:id', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/warehouses/warehouse-form/warehouse-form.component').then(m => m.WarehouseFormComponent) },
      { path: 'purchase-orders/edit/:id', canActivate: [roleGuard], data: { roles: operational }, loadComponent: () => import('./features/purchases/purchase-orders/purchase-order-form/purchase-order-form.component').then(m => m.PurchaseOrderFormComponent) },
      { path: 'employees/edit/:id', canActivate: [roleGuard], data: { roles: admin }, loadComponent: () => import('./features/hr/employee-form/employee-form.component').then(m => m.EmployeeFormComponent) },
      { path: 'prescriptions/edit/:id', canActivate: [roleGuard], data: { roles: authenticated }, loadComponent: () => import('./features/prescriptions/prescription-form/prescription-form.component').then(m => m.PrescriptionFormComponent) },
    ],
  },
  { path: 'login', loadComponent: () => import('./features/auth/login/login.component').then(m => m.LoginComponent) },
  { path: 'forgot-password', loadComponent: () => import('./features/auth/forgot-password/forgot-password.component').then(m => m.ForgotPasswordComponent) },
  { path: '**', redirectTo: '' },
];
